// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoys22emmEOB8Eu8GYMNQLQUbHGAC-u8g',
    appId: '1:521320658524:web:3f6544bacfde6256fe5899',
    messagingSenderId: '521320658524',
    projectId: 'mealdbauth',
    authDomain: 'mealdbauth.firebaseapp.com',
    storageBucket: 'mealdbauth.firebasestorage.app',
    measurementId: 'G-RRC9KSJSQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HxOZiSjVeMRPBnCfA-uCOEgTGSM-Wfw',
    appId: '1:521320658524:android:50b9db5ca6c987dafe5899',
    messagingSenderId: '521320658524',
    projectId: 'mealdbauth',
    storageBucket: 'mealdbauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFnIUyEAWFkvvN5w3ZE4aKs3lGccYGn3M',
    appId: '1:521320658524:ios:12d0497b923a4d36fe5899',
    messagingSenderId: '521320658524',
    projectId: 'mealdbauth',
    storageBucket: 'mealdbauth.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFnIUyEAWFkvvN5w3ZE4aKs3lGccYGn3M',
    appId: '1:521320658524:ios:12d0497b923a4d36fe5899',
    messagingSenderId: '521320658524',
    projectId: 'mealdbauth',
    storageBucket: 'mealdbauth.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoys22emmEOB8Eu8GYMNQLQUbHGAC-u8g',
    appId: '1:521320658524:web:786f9b7f8d3b2cc0fe5899',
    messagingSenderId: '521320658524',
    projectId: 'mealdbauth',
    authDomain: 'mealdbauth.firebaseapp.com',
    storageBucket: 'mealdbauth.firebasestorage.app',
    measurementId: 'G-4BPW9XN5DV',
  );

}