// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'mealdbauth',
    authDomain: 'mealdbauth.firebaseapp.com',
    storageBucket: 'mealdbauth.firebasestorage.app',
    measurementId: 'G-RRC9KSJSQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'mealdbauth',
    storageBucket: 'mealdbauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'mealdbauth',
    storageBucket: 'mealdbauth.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'mealdbauth',
    storageBucket: 'mealdbauth.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'x',
    projectId: 'mealdbauth',
    authDomain: 'mealdbauth.firebaseapp.com',
    storageBucket: 'mealdbauth.firebasestorage.app',
    measurementId: 'G-4BPW9XN5DV',
  );

}
